import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// Fully static: the game data lives in public/data (generated by
// tools/build-corpus.js), so there is no API server to proxy to.
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
  },
});
